// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmWcFKalt4I_VXaaO0ZVcIdjYXQFyEDgA',
    appId: '1:1031393199408:web:83b1319b2418ec42cdf4f5',
    messagingSenderId: '1031393199408',
    projectId: 'flutter-app-distribution-3c656',
    authDomain: 'flutter-app-distribution-3c656.firebaseapp.com',
    storageBucket: 'flutter-app-distribution-3c656.firebasestorage.app',
    measurementId: 'G-3SB4CG61W3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaAY_Omsfc4TVg58O8IUEHw_qgntH2WBQ',
    appId: '1:1031393199408:android:a217b7f313d275fecdf4f5',
    messagingSenderId: '1031393199408',
    projectId: 'flutter-app-distribution-3c656',
    storageBucket: 'flutter-app-distribution-3c656.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVC52XXq6VZUkF_-Jsxm2xX1M9ZWdOTLI',
    appId: '1:1031393199408:ios:ae08caa056c67c72cdf4f5',
    messagingSenderId: '1031393199408',
    projectId: 'flutter-app-distribution-3c656',
    storageBucket: 'flutter-app-distribution-3c656.firebasestorage.app',
    iosBundleId: 'com.example.advanced',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVC52XXq6VZUkF_-Jsxm2xX1M9ZWdOTLI',
    appId: '1:1031393199408:ios:ae08caa056c67c72cdf4f5',
    messagingSenderId: '1031393199408',
    projectId: 'flutter-app-distribution-3c656',
    storageBucket: 'flutter-app-distribution-3c656.firebasestorage.app',
    iosBundleId: 'com.example.advanced',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmWcFKalt4I_VXaaO0ZVcIdjYXQFyEDgA',
    appId: '1:1031393199408:web:79d104b5d258df22cdf4f5',
    messagingSenderId: '1031393199408',
    projectId: 'flutter-app-distribution-3c656',
    authDomain: 'flutter-app-distribution-3c656.firebaseapp.com',
    storageBucket: 'flutter-app-distribution-3c656.firebasestorage.app',
    measurementId: 'G-K53WMC7D4Z',
  );
}
